### ISSUE TITLE
Add Ubuntu font from CDN

### ISSUE THREAD

**Issue by tassoskoutlas** [greekdigitalcommunity/greekdigitalcommunity.github.io#7]
Macs don't have it by default so the site does not look right.

**Comment by matrixlord** [comment]
I would suggest to add
`https://fonts.googleapis.com/css?family=Ubuntu&amp;subset=greek`
instead of
`https://fonts.googleapis.com/css?family=Ubuntu`
just to be sure.

Do you mind if I merge the PR and then change the link directly to master?

**Comment by tassoskoutlas** [comment]
Feel free to push the commit to change it. And I don't mind at all on anything. If you think something is better I am sure you think it for good reason so feel free to go ahead :)

**Comment by matrixlord** [comment]
As my commit suggests, I added font to CSS file instead of every HTML page.

(I am closing the issue)

**Comment by smosgr** [comment]
👍
